#!/bin/sh

MY_PATH="`dirname \"$0\"`"
NPM_BIN_PATH="$MY_PATH/../node_modules/.bin"
$MY_PATH/clean

$NPM_BIN_PATH/babel -s --watch "$MY_PATH/../src" --copy-files --out-dir "$MY_PATH/../build" &
$NPM_BIN_PATH/webpack --watch --config "$MY_PATH/../webpack.config.js" &

wait
